blogs/urls.py
from django.urls import path

from . import views

# Add a namespace

app_name = 'blogs'

urlpatterns = [
    path('', views.blog_front, name='blog_front'),
    path('post/<int:post_id>/', views.post_details, name='post_details'),
    path('newpost/', views.newpost, name='newpost'),
    path('welcome/(?P<username>\w+)/$', views.welcome, name='welcome'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout')
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # path('blogs/', include('blogs.urls')),
    # path('asciichan/', include('asciichan.urls')),
    path('theora/', include('theora.urls')),
    path('admin/', admin.site.urls),
]

blogs/models.py
from django.db import models
from django.template import loader


class User(models.Model):
    username = models.CharField(max_length=128)
    password = models.CharField(max_length=512)
    email = models.CharField(max_length=128)


class Post(models.Model):
    subject = models.CharField(max_length=128)
    content = models.CharField(max_length=1024)
    created = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

    def render(self):
        self.render_text = self.content.replace('\n', '<br>')
        template = loader.get_template('blogs/post.html')
        return template.render({'p': self})


class NewsPost(models.Model):
    title = models.CharField(max_length=256)
    link = models.CharField(max_length=256)
    description = models.CharField(max_length=256)
    pub_date = models.DateTimeField(max_length=512)
    guid = models.CharField(max_length=64)
    articletype = models.CharField(max_length=32)

blogs/views.py
import re
import hmac
import random
import hashlib
from string import ascii_letters
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Post, User
from django.urls import reverse


secret = 'fart'

USER_RE = re.compile(r"^[a-zA-Z0-9_-]{3,20}$")
def valid_username(username):
    return username and USER_RE.match(username)


PASS_RE = re.compile(r"^.{3,20}$")
def valid_password(password):
    return password and PASS_RE.match(password)


EMAIL_RE = re.compile(r'^[\S]+@[\S]+\.[\S]+$')
def valid_email(email):
    return not email or EMAIL_RE.match(email)

def make_salt(length = 5):
    return (''.join(random.choice(ascii_letters) for x in range(length)))

def make_pw_hash(name, password, salt = None):
    # nm = name
    # pw = password
    if not salt:
        salt = make_salt()
    h = hashlib.sha256((name + password + salt).encode('utf-8')).hexdigest()
    return '{},{}'.format(salt, h)

def valid_pw(name, password, h):
    salt = h.split(',')[0]
    return h == make_pw_hash(name, password, salt)


def login(request):
    if request.method == "GET":
        return render(request, 'blogs/login-form.html')
    elif request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']

        # Look up users
        u = User.objects.get(username=username)
        if u and valid_pw(username, password, u.password):
            # response = blog_front(request)
            response = HttpResponseRedirect(reverse('blogs:welcome', kwargs={'username': username}))
            # response = HttpResponseRedirect('/blogs/welcome', {'username': 'AAA'})
            cookie_value = make_secure_val(u.id)
            response.set_cookie(key='user_id', value=cookie_value)
            return response
        else:
            msg = 'Invalid login'
            context = {
                'error': msg
            }
            return render(request, 'blogs/login-form.html', context)

def logout(request):
    response = HttpResponseRedirect('/blogs/signup')
    response.delete_cookie(key='user_id')
    return response

def blog_front(request):
    # block user WO cookie
    user_cookie = request.COOKIES.get('user_id')
    if not user_cookie:
        return HttpResponseRedirect(reverse('blogs:signup'))
    user_id, h = user_cookie.split('|')
    if not user_id.isdigit():
        return HttpResponseRedirect(reverse('blogs:signup'))
    if not h == hmac.new(secret.encode('utf-8'), user_id.encode('utf-8'),
             digestmod='sha256').hexdigest():
        return HttpResponseRedirect(reverse('blogs:signup'))

    latest_posts_list = Post.objects.order_by('-last_modified')[:5]
    context = {
        'posts': latest_posts_list,
    }
    return render(request, 'blogs/front.html', context)


def post_details(request, post_id):
    post = Post.objects.get(pk=post_id)
    context = {'post': post}
    return render(request, 'blogs/permalink.html', context)


def newpost(request):
    if request.method == "GET":
        return render(request, 'blogs/newpost.html')
    elif request.method == "POST":
        subject = request.POST['subject']
        content = request.POST['content']

        if subject and content:
            p = Post(subject=subject, content=content)
            p.save()
            return HttpResponseRedirect('/blogs/post/{post_id}'.format(post_id=p.id))
        else:
            error = "subject and content, please!"
            context = {
                'subject': subject,
                'content': content,
                'error': error
            }
            render("newpost.html", context)


def welcome(request, username):
    # context = {'username': request.GET['username']}
    context = {'username': username}
    return render(request, 'blogs/welcome.html', context)


def make_secure_val(val):
    return '{}|{}'.format(val,
                          hmac.new(secret.encode('utf-8'),
                                   str(val).encode('utf-8'),
                                   digestmod='sha256').hexdigest())


def register_user(name, password, email):
    """
    """
    pw_hash = make_pw_hash(name, password)
    return User(username=name,
                password=pw_hash,
                email=email)

# TODO: put it in DB
def signup(request, **kwargs):
    if request.method == "GET":
        return render(request, 'blogs/signup-form.html', kwargs)
    elif request.method == "POST":
        have_error = False
        username = request.POST['username']
        password = request.POST['password']
        verify = request.POST['verify']
        email = request.POST['email']

        params = {'username': username, 'email': email}

        if not valid_username(username):
            params['error_username'] = "That's not a valid username."
            have_error = True

        if not valid_password(password):
            params['error_password'] = "That wasn't a valid password."
            have_error = True
        elif password != verify:
            params['error_verify'] = "Your passwords didn't match."
            have_error = True

        if not valid_email(email):
            params['error_email'] = "That's not a valid email."
            have_error = True

        if have_error:
            return render(request, 'blogs/signup-form.html', params)
        else:
            try:
                u = User.objects.get(username=username)
            except User.DoesNotExist:
                u = None
            if u:
                msg = 'That user already exists.'
                params['error_username'] = msg
                return render(request, 'blogs/signup-form.html', params)
            else:
                # This is new user
                u = register_user(name=username, password=password, email=email)
                u.save()
                rep = HttpResponseRedirect('/blogs/')
                rep.set_cookie(key='user_id', value=make_secure_val(u.id))
                return rep

blogs/templates/blogs/base.html
<!DOCTYPE html>
<html>
<head>
  <link type="text/css" rel="stylesheet" href="/static/main.css" />

  <title>My Site</title>
</head>

<body>
  <a href="/blogs/" class="main-title">
    My Site
  </a>

  <div id="content">
  {% block content %}
  {% endblock %}
  </div>
</body>

</html>

blogs/templates/blogs/front.html
{% extends "blogs/base.html" %}

{% block content %}

  {% for post in posts %}
      {{ post.render }}
      <br><br>
  {% endfor %}

{% endblock %}

blogs/templates/blogs/newpost.html
{% extends "blogs/base.html" %}

{% block content %}
  <h2>new post</h2>

    <form method="post">
      {% csrf_token %}
      <label>
        <div>subject</div>
        <input type="text" name="subject" value="{{subject}}">
      </label>

      <label>
        <div>blog</div>
        <textarea name="content">{{content}}</textarea>
      </label>

      <div class="error">{{error}}</div>

      <input type="submit">
    </form>
{% endblock %}

blogs/templates/blogs/permalink.html
{% extends "blogs/base.html" %}

{% block content %}
    {{ post.render }}
{% endblock %}

blogs/templates/blogs/post.html
<div class="post">
  <div class="post-heading">
    <div class="post-title">
      {{p.subject}}
    </div>

    <div class="post-date">
      {{p.created|date:'Y-m-d H:i'}}
    </div>
  </div>

  <div class="post-content">
    {{p.render_text}}
  </div>
</div>

blogs/templates/blogs/signup-form.html
<!DOCTYPE html>

<html>
  <head>
    <title>User Sign Up</title>
    <style type="text/css">
      .label {text-align: right}
      .error {color: red}
    </style>

  </head>

  <body>
    <h2>Signup</h2>
    <form action="{% url 'blogs:signup' %}" method="post">
      {% csrf_token %}
      <table>
        <tr>
          <td class="label">
            Username
          </td>
          <td>
            <input type="text" name="username" value="{{username}}">
          </td>
          <td class="error">
            {{error_username}}
          </td>
        </tr>

        <tr>
          <td class="label">
            Password
          </td>
          <td>
            <input type="password" name="password" value="">
          </td>
          <td class="error">
            {{error_password}}
          </td>
        </tr>

        <tr>
          <td class="label">
            Verify Password
          </td>
          <td>
            <input type="password" name="verify" value="">
          </td>
          <td class="error">
            {{error_verify}}
          </td>
        </tr>

        <tr>
          <td class="label">
            Email (optional)
          </td>
          <td>
            <input type="text" name="email" value="{{email}}">
          </td>
          <td class="error">
            {{error_email}}
          </td>
        </tr>
      </table>

      <input type="submit">
    </form>
  </body>

</html>

blogs/templates/blogs/welcome.html
{% extends "blogs/base.html" %}

{% block content %}

  <p>Welcome back, {{ username }}!</p>
  <p>After 3 seconds you will be redirected to the front page</p>
  <meta http-equiv="refresh" content="3;url={% url 'blogs:blog_front' %}">

{% endblock %}