blogs/urls.py
from django.urls import path

from . import views

# Add a namespace

app_name = 'blogs'

urlpatterns = [
    path('', views.blog_front, name='blog_front'),
    path('post/<int:post_id>/', views.post_details, name='post_details'),
    path('newpost/', views.newpost, name='newpost'),
    path('welcome/(?P<username>\w+)/$', views.welcome, name='welcome'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout')
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # path('blogs/', include('blogs.urls')),
    # path('asciichan/', include('asciichan.urls')),
    path('theora/', include('theora.urls')),
    path('admin/', admin.site.urls),
]

theora/urls.py
from django.urls import path

from . import views

# Add a namespace

app_name = 'theora'

urlpatterns = [
    path('', views.theora_front, name='theora_front'),
    # path('post/<int:post_id>/', views.post_details, name='post_details'),
    # path('newpost/', views.newpost, name='newpost'),
    path('welcome/(?P<username>\w+)/$', views.welcome, name='welcome'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('shengyipan/', views.aboutme, name='aboutme')
]

theora/models.py
from django.db import models
from django.template import loader

# Create your models here.

class NewsFeed(models.Model):
    news_source = models.CharField(max_length=32)
    title = models.CharField(max_length=256)
    link = models.CharField(max_length=256)
    description = models.CharField(max_length=1024)
    pub_date = models.DateTimeField(auto_now=False)
    article_type = models.CharField(max_length=32)
    language = models.CharField(max_length=5)
    sentiment = models.CharField(max_length=1024)

    def render(self):
        self.render_text = self.description.replace('\n', '<br>')
        template = loader.get_template('theora/post.html')
        return template.render({'p': self})

class User(models.Model):
    username = models.CharField(max_length=128)
    password = models.CharField(max_length=512)
    email = models.CharField(max_length=128)

theora/views.py
import re
import hmac
import random
import hashlib
from string import ascii_letters
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import NewsFeed, User
from django.urls import reverse

secret = 'fart'
invitation_code = 'invite-me-VIP'

USER_RE = re.compile(r"^[a-zA-Z0-9_-]{3,20}$")
PASS_RE = re.compile(r"^.{3,20}$")
EMAIL_RE = re.compile(r'^[\S]+@[\S]+\.[\S]+$')


def valid_username(username):
    return username and USER_RE.match(username)


def valid_password(password):
    return password and PASS_RE.match(password)


def valid_email(email):
    return not email or EMAIL_RE.match(email)


def make_salt(length=5):
    return (''.join(random.choice(ascii_letters) for x in range(length)))


def make_pw_hash(name, password, salt=None):
    # nm = name
    # pw = password
    if not salt:
        salt = make_salt()
    h = hashlib.sha256((name + password + salt).encode('utf-8')).hexdigest()
    return '{},{}'.format(salt, h)


def valid_pw(name, password, h):
    salt = h.split(',')[0]
    return h == make_pw_hash(name, password, salt)


def make_secure_val(val):
    return '{}|{}'.format(val,
                          hmac.new(secret.encode('utf-8'),
                                   str(val).encode('utf-8'),
                                   digestmod='sha256').hexdigest())


def register_user(name, password, email):
    """
    """
    pw_hash = make_pw_hash(name, password)
    return User(username=name,
                password=pw_hash,
                email=email)


def login(request):
    if request.method == "GET":
        return render(request, 'theora/login-form.html')
    elif request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']

        # Look up users
        u = User.objects.get(username=username)
        if u and valid_pw(username, password, u.password):
            response = HttpResponseRedirect(reverse('theora:welcome', kwargs={'username': username}))
            cookie_value = make_secure_val(u.id)
            response.set_cookie(key='user_id', value=cookie_value)
            return response
        else:
            msg = 'Invalid login'
            context = {
                'error': msg
            }
            return render(request, 'theora/login-form.html', context)


def logout(request):
    response = HttpResponseRedirect('/theora/signup')
    response.delete_cookie(key='user_id')
    return response


def welcome(request, username):
    # context = {'username': request.GET['username']}
    context = {'username': username}
    return render(request, 'theora/welcome.html', context)


def theora_front(request):
    # block user WO cookie
    user_cookie = request.COOKIES.get('user_id')
    if not user_cookie:
        return HttpResponseRedirect(reverse('theora:signup'))
    user_id, h = user_cookie.split('|')
    if not user_id.isdigit():
        return HttpResponseRedirect(reverse('theora:signup'))
    if not h == hmac.new(secret.encode('utf-8'), user_id.encode('utf-8'),
                         digestmod='sha256').hexdigest():
        return HttpResponseRedirect(reverse('theora:signup'))

    latest_posts_list = NewsFeed.objects.order_by('-pub_date')[:5]
    context = {
        'posts': latest_posts_list,
    }
    return render(request, 'theora/theora-front.html', context)


def signup(request, **kwargs):
    if request.method == "GET":
        return render(request, 'theora/signup-form.html', kwargs)
    elif request.method == "POST":
        have_error = False
        username = request.POST['username']
        password = request.POST['password']
        verify = request.POST['verify']
        email = request.POST['email']
        invitation = request.POST['invitation']

        params = {'username': username, 'email': email}

        if not invitation or invitation != invitation_code:
            params['error_invitation'] = "You need an invitation code for sign up."
            have_error = True

        if not valid_username(username):
            params['error_username'] = "That's not a valid username."
            have_error = True

        if not valid_password(password):
            params['error_password'] = "That wasn't a valid password."
            have_error = True
        elif password != verify:
            params['error_verify'] = "Your passwords didn't match."
            have_error = True

        if not valid_email(email):
            params['error_email'] = "That's not a valid email."
            have_error = True

        if have_error:
            return render(request, 'theora/signup-form.html', params)

        try:
            u = User.objects.get(username=username)
        except User.DoesNotExist:
            u = None
        if u:
            msg = 'That user already exists.'
            params['error_username'] = msg
            return render(request, 'theora/signup-form.html', params)
        else:
            # This is new user
            u = register_user(name=username, password=password, email=email)
            u.save()
            rep = HttpResponseRedirect('/theora/')
            rep.set_cookie(key='user_id', value=make_secure_val(u.id))
            return rep


def aboutme(request):
    return render(request, 'theora/about-me.html')

theora/templates/theora/about-me.html
<!DOCTYPE html>
<html lang="en">

<table style="width: 100%; border-collapse: collapse; border-style: none;" border="0">
    <tbody>
    <tr>
        <td style="width: 60px; text-align: center;"><a href="/theora/">Home</a></td>
        <td style="width: 120px; text-align: center;"><a href="/theora/shengyipan">About Me</a></td>
        <td style="text-align: right;">&nbsp;</td>
    </tr>
    </tbody>
</table>

<head>
    <meta charset="UTF-8">
    <title>About Me</title>
</head>
<body>

<table style="width: 100%; border-collapse: collapse; height: 620px;" border="0">
    <tbody>
    <tr style="height: 445px;">
        <td style="width: 100%; height: 445px;">
            {% load static %}
            <img src="{% static '/images/me.jpeg' %}" alt="Me" width="640" height="441"/>
        </td>
    </tr>
    <tr style="height: 61px;">
        <td style="width: 100%; height: 61px;">
            <h2>Shengyi Pan</h2>
        </td>
    </tr>
    <tr style="height: 114px;">
        <td style="width: 100%; height: 114px;">
            <p>Father, PhD, Full Stack Software Engineer, Big Data Engineer,&nbsp;Current Amazonian; ex-IBMer,
                ex-Netflix, ex-Tencent.</p>
            <p>I am specialized in building efficient, reliable, scalable software that powers various BI and
                machine learning use cases.</p>
            <p>In my spare time, I enjoy reading, listening to music, running, biking, watching NBA and NFL. I am
                blockchain amateur. I mine cryptocurrency with my self-built mining rig. I am also interested in developing
                dApps.</p>
        </td>
    </tr>
    </tbody>
</table>
</body>
</html>

theora/templates/theora/base.html
<!DOCTYPE html>
<html>
<table style="width: 100%; border-collapse: collapse; border-style: none;" border="0">
    <tbody>
    <tr>
        <td style="width: 60px; text-align: center;"><a href="/theora/">Home</a></td>
        <td style="width: 120px; text-align: center;"><a href="/theora/shengyipan">About Me</a></td>
        <td style="text-align: right;">&nbsp;</td>
        <td style="width: 60px; text-align: right;"><a href="/theora/signup">Sign Up</a></td>
        <td style="width: 60px; text-align: right;"><a href="/theora/logout">Log Out</a></td>
    </tr>
    </tbody>
</table>

<head>
    <link type="text/css" rel="stylesheet" href="/static/main.css"/>
    <title>My Site</title>
</head>

<body>
<a href="/theora/" class="main-title">
    Theora
</a>
<h3 style="text-align: center;">Media Article Sentiment Analysis</h3>

<hr/>

<table style="height: 333px; width: 100%; border-collapse: collapse;" border="0">
    <tbody>
    <tr style="height: 30px;">
        <td style="width: 80%; height: 333px;" rowspan="4">
            <div id="content">
                {% block content %}
                {% endblock %}
            </div>
        </td>
        <td style="width: 20%; height: 25px; text-align: center;">News Sources</td>
    </tr>
    <tr style="height: 200px;">
        <td style="width: 20%; height: 119px;">Coming soon</td>
    </tr>
    <tr style="height: 30px;">
        <td style="width: 20%; height: 20px; text-align: center;">Archives</td>
    </tr>
    <tr style="height: 200px;">
        <td style="width: 18.17447495961228%; height: 169px;">Coming soon</td>
    </tr>
    </tbody>
</table>

<hr/>

<table style="width: 100%; border-collapse: collapse;" border="0">
    <tbody>
    <tr>
        <td style="width: 100%; text-align: center;">Pages 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10</td>
    </tr>
    </tbody>
</table>
</body>

</html>

theora/templates/theora/login-form.html
<!DOCTYPE html>

<html>
  <head>
    <title>Login</title>
    <style type="text/css">
      .label {text-align: right}
      .error {color: red}
    </style>

  </head>

  <body>
    <h2>Login</h2>
    <form method="post">
      {% csrf_token %}
      <table>
        <tr>
          <td class="label">
            Username
          </td>
          <td>
            <input type="text" name="username" value="{{username}}">
          </td>
        </tr>

        <tr>
          <td class="label">
            Password
          </td>
          <td>
            <input type="password" name="password" value="">
          </td>
        </tr>
      </table>

      <div class="error">
        {{error}}
      </div>

      <input type="submit">
    </form>
  </body>

</html>

theora/templates/theora/post.html
<div class="post">
  <div class="post-heading">
    <div class="post-title">
      {{p.news_source}}: {{p.title}}
    </div>

    <div class="post-date">
      {{p.pub_date|date:'Y-m-d H:i'}}, {{p.article_type}}
    </div>
  </div>

  <div class="post-content">
    <p> {{p.render_text}} </p>
    <p> Sentiment Analysis: {{p.sentiment}} </p>
  </div>
</div>

theora/templates/theora/signup-form.html
<!DOCTYPE html>

<html>
<head>
    <title>User Sign Up</title>
    <style type="text/css">
      .label {text-align: right}
      .error {color: red}
    </style>

</head>

<body>
<h2>Signup</h2>
<form action="{% url 'theora:signup' %}" method="post">
    {% csrf_token %}
    <table>
        <tr>
            <td class="label">
                Username
            </td>
            <td>
                <input type="text" name="username" value="{{username}}">
            </td>
            <td class="error">
                {{error_username}}
            </td>
        </tr>

        <tr>
            <td class="label">
                Password
            </td>
            <td>
                <input type="password" name="password" value="">
            </td>
            <td class="error">
                {{error_password}}
            </td>
        </tr>

        <tr>
            <td class="label">
                Verify Password
            </td>
            <td>
                <input type="password" name="verify" value="">
            </td>
            <td class="error">
                {{error_verify}}
            </td>
        </tr>

        <tr>
            <td class="label">
                Email (optional)
            </td>
            <td>
                <input type="text" name="email" value="{{email}}">
            </td>
            <td class="error">
                {{error_email}}
            </td>
        </tr>

        <tr>
            <td class="label">
                Invitation Code
            </td>
            <td>
                <input type="text" name="invitation" value="">
            </td>
            <td class="error">
                {{error_invitation}}
            </td>
        </tr>
    </table>

    <input type="submit">
</form>
<p> or <a href="/theora/login">Sign In</a></p>
</body>

</html>

theora/templates/theora/theora-front.html
{% extends "theora/base.html" %}

{% block content %}

  {% for post in posts %}
      {{ post.render }}
      <br><br>
  {% endfor %}

{% endblock %}

theora/templates/theora/welcome.html
{% extends "theora/base.html" %}

{% block content %}

  <p>Welcome back, {{ username }}!</p>
  <p>After 5 seconds you will be redirected to the front page</p>
  <meta http-equiv="refresh" content="5;url={% url 'theora:theora_front' %}">

{% endblock %}